import { SCOPE } from './security.js';
import { cfg,discord,slim,allowGuild,allowChannel,assertGuild,assertChannel } from './discord.js';
const ann={readOnlyHint:true,destructiveHint:false,openWorldHint:false};
const sec=[{type:'oauth2',scopes:[SCOPE]}];
export const tools=[
{name:'discord_get_profile',title:'Get Discord connection profile',description:'Return the connected Discord bot identity and visible server count. Read-only.',inputSchema:{type:'object',properties:{},additionalProperties:false},securitySchemes:sec,annotations:ann},
{name:'discord_list_guilds',title:'List Discord servers',description:'List Discord servers visible to the bot. Read-only.',inputSchema:{type:'object',properties:{},additionalProperties:false},securitySchemes:sec,annotations:ann},
{name:'discord_list_channels',title:'List Discord channels',description:'List channels in one Discord server. Read-only.',inputSchema:{type:'object',required:['guild_id'],additionalProperties:false,properties:{guild_id:{type:'string'}}},securitySchemes:sec,annotations:ann},
{name:'discord_list_active_threads',title:'List active Discord threads',description:'List active threads in one Discord server. Read-only.',inputSchema:{type:'object',required:['guild_id'],additionalProperties:false,properties:{guild_id:{type:'string'}}},securitySchemes:sec,annotations:ann},
{name:'discord_get_messages',title:'Read Discord channel messages',description:'Read up to 100 recent or paginated messages from a text channel or thread. Read-only.',inputSchema:{type:'object',required:['channel_id'],additionalProperties:false,properties:{channel_id:{type:'string'},limit:{type:'integer',minimum:1,maximum:100,default:50},before:{type:'string'},after:{type:'string'},around:{type:'string'}}},securitySchemes:sec,annotations:ann},
{name:'discord_get_message',title:'Read one Discord message',description:'Read one Discord message. Read-only.',inputSchema:{type:'object',required:['channel_id','message_id'],additionalProperties:false,properties:{channel_id:{type:'string'},message_id:{type:'string'}}},securitySchemes:sec,annotations:ann},
{name:'discord_search_messages',title:'Search Discord messages',description:'Search message history in a server. Requires message-history access and Message Content intent. Read-only.',inputSchema:{type:'object',required:['guild_id'],additionalProperties:false,properties:{guild_id:{type:'string'},content:{type:'string',maxLength:1024},channel_ids:{type:'array',items:{type:'string'},maxItems:500},author_ids:{type:'array',items:{type:'string'},maxItems:100},limit:{type:'integer',minimum:1,maximum:25,default:25},offset:{type:'integer',minimum:0,maximum:9975},sort_by:{type:'string',enum:['timestamp','relevance']},sort_order:{type:'string',enum:['asc','desc']}}},securitySchemes:sec,annotations:ann}
];
const out=v=>({content:[{type:'text',text:JSON.stringify(v,null,2)}]});
export async function callTool(name,a={}){
 const c=cfg();
 if(name==='discord_get_profile'){const me=(await discord('/users/@me',c)).data;const gs=(await discord('/users/@me/guilds',c,{limit:200,with_counts:true})).data||[];return out({bot:{id:me.id,username:me.username,global_name:me.global_name},visible_guilds:gs.filter(g=>allowGuild(g.id,c)).length});}
 if(name==='discord_list_guilds'){const gs=(await discord('/users/@me/guilds',c,{limit:200,with_counts:true})).data||[];return out(gs.filter(g=>allowGuild(g.id,c)).map(g=>({id:g.id,name:g.name,icon:g.icon,approximate_member_count:g.approximate_member_count,approximate_presence_count:g.approximate_presence_count})));}
 if(name==='discord_list_channels'){assertGuild(a.guild_id,c);const xs=(await discord('/guilds/'+encodeURIComponent(a.guild_id)+'/channels',c)).data||[];return out(xs.filter(x=>allowChannel(x.id,c)).map(x=>({id:x.id,name:x.name,type:x.type,parent_id:x.parent_id,position:x.position,topic:x.topic})));}
 if(name==='discord_list_active_threads'){assertGuild(a.guild_id,c);const x=(await discord('/guilds/'+encodeURIComponent(a.guild_id)+'/threads/active',c)).data||{};return out({threads:(x.threads||[]).filter(t=>allowChannel(t.id,c)).map(t=>({id:t.id,name:t.name,parent_id:t.parent_id,owner_id:t.owner_id,message_count:t.message_count,member_count:t.member_count,thread_metadata:t.thread_metadata}))});}
 if(name==='discord_get_messages'){assertChannel(a.channel_id,c);const xs=(await discord('/channels/'+encodeURIComponent(a.channel_id)+'/messages',c,{limit:a.limit||50,before:a.before,after:a.after,around:a.around})).data||[];return out(xs.map(slim));}
 if(name==='discord_get_message'){assertChannel(a.channel_id,c);return out(slim((await discord('/channels/'+encodeURIComponent(a.channel_id)+'/messages/'+encodeURIComponent(a.message_id),c)).data));}
 if(name==='discord_search_messages'){assertGuild(a.guild_id,c);for(const id of a.channel_ids||[])assertChannel(id,c);let r=await discord('/guilds/'+encodeURIComponent(a.guild_id)+'/messages/search',c,{content:a.content,channel_id:a.channel_ids,author_id:a.author_ids,limit:a.limit||25,offset:a.offset||0,sort_by:a.sort_by,sort_order:a.sort_order});if(r.status===202){await new Promise(z=>setTimeout(z,Math.min(3000,Math.max(1000,Number(r.data?.retry_after||1)*1000))));r=await discord('/guilds/'+encodeURIComponent(a.guild_id)+'/messages/search',c,{content:a.content,channel_id:a.channel_ids,author_id:a.author_ids,limit:a.limit||25,offset:a.offset||0,sort_by:a.sort_by,sort_order:a.sort_order});}return out({total_results:r.data?.total_results||0,doing_deep_historical_index:!!r.data?.doing_deep_historical_index,messages:(r.data?.messages||[]).flat().map(slim)});}
 throw new Error('unknown tool: '+name);
}
