import { SCOPE,baseUrl,sign,verify,passwordOk,pkce,issueAccess,verifyAccess,readJson,readForm,esc } from './lib/security.js';
import { tools,callTool } from './lib/tools.js';
function json(res,s,b,h={}){res.statusCode=s;res.setHeader('content-type','application/json; charset=utf-8');for(const[k,v]of Object.entries(h))res.setHeader(k,v);res.end(JSON.stringify(b));}
function html(res,s,b){res.statusCode=s;res.setHeader('content-type','text/html; charset=utf-8');res.end(b);}
function cors(res){res.setHeader('access-control-allow-origin','*');res.setHeader('access-control-allow-methods','GET,POST,OPTIONS');res.setHeader('access-control-allow-headers','content-type,authorization,mcp-session-id,mcp-protocol-version');}
function route(req){return new URL(req.url||'/','https://x.invalid').searchParams.get('route')||'';}
function challenge(req,res){const b=baseUrl(req);json(res,401,{error:'unauthorized'},{'www-authenticate':'Bearer resource_metadata="'+b+'/.well-known/oauth-protected-resource"'});}
function validClient(id,redirect){const c=verify(id,'dr_cl');if(c.typ!=='client'||!c.redirect_uris?.includes(redirect))throw new Error('invalid client');return c;}
async function register(req,res){if(req.method!=='POST')return json(res,405,{error:'method_not_allowed'});const b=await readJson(req);const rs=(b.redirect_uris||[]).filter(x=>typeof x==='string'&&x.startsWith('https://'));if(!rs.length)return json(res,400,{error:'invalid_redirect_uris'});const now=Math.floor(Date.now()/1000);const id=sign('dr_cl',{typ:'client',redirect_uris:rs,iat:now,exp:now+31536000});json(res,201,{client_id:id,client_id_issued_at:now,redirect_uris:rs,grant_types:['authorization_code'],response_types:['code'],token_endpoint_auth_method:'none'});}
function checkAuth(p,b){validClient(p.client_id,p.redirect_uri);if(p.response_type!=='code')throw new Error('response_type');if(!p.code_challenge||p.code_challenge_method!=='S256')throw new Error('PKCE S256 required');const scope=p.scope||SCOPE;if(!scope.split(/\s+/).includes(SCOPE))throw new Error('scope required');const resource=p.resource||b;if(resource!==b)throw new Error('invalid resource');return{scope,resource};}
async function authorize(req,res){const b=baseUrl(req);if(req.method==='GET'){const p=Object.fromEntries(new URL(req.url||'/','https://x.invalid').searchParams.entries());try{checkAuth(p,b)}catch(e){return html(res,400,'<p>Invalid OAuth request: '+esc(e.message)+'</p>')}const hs=['client_id','redirect_uri','response_type','scope','state','code_challenge','code_challenge_method','resource'].map(k=>'<input type="hidden" name="'+esc(k)+'" value="'+esc(p[k]||'')+'">').join('');return html(res,200,'<!doctype html><meta name="viewport" content="width=device-width"><title>Discord Reader</title><body style="font-family:system-ui;max-width:520px;margin:10vh auto;padding:24px"><h1>Connect Discord Reader</h1><p>Read-only access limited by the Discord bot permissions and optional allowlists.</p><form method="post" action="/oauth/authorize">'+hs+'<label>Connection password<br><input required autofocus type="password" name="password" style="width:100%;padding:10px;margin:8px 0 16px"></label><button>Authorize ChatGPT</button></form>');}
 if(req.method!=='POST')return json(res,405,{error:'method_not_allowed'});const p=await readForm(req);try{const x=checkAuth(p,b);if(!passwordOk(p.password))return html(res,403,'<p>Invalid password</p>');const now=Math.floor(Date.now()/1000);const code=sign('dr_cd',{typ:'code',client_id:p.client_id,redirect_uri:p.redirect_uri,resource:x.resource,scope:x.scope,code_challenge:p.code_challenge,iat:now,exp:now+300});const u=new URL(p.redirect_uri);u.searchParams.set('code',code);if(p.state)u.searchParams.set('state',p.state);res.statusCode=302;res.setHeader('location',u.toString());res.end();}catch(e){html(res,400,'<p>Authorization failed: '+esc(e.message)+'</p>');}}
async function token(req,res){if(req.method!=='POST')return json(res,405,{error:'method_not_allowed'});const p=await readForm(req);const b=baseUrl(req);try{if(p.grant_type!=='authorization_code')throw new Error('unsupported grant');validClient(p.client_id,p.redirect_uri);const c=verify(p.code,'dr_cd');if(c.typ!=='code'||c.client_id!==p.client_id||c.redirect_uri!==p.redirect_uri||c.resource!==b||pkce(p.code_verifier)!==c.code_challenge)throw new Error('invalid authorization code');json(res,200,{access_token:issueAccess(p.client_id,b,c.scope),token_type:'Bearer',expires_in:2592000,scope:c.scope||SCOPE});}catch(e){json(res,400,{error:'invalid_grant',error_description:e.message});}}
async function mcp(req,res){try{verifyAccess(req)}catch{return challenge(req,res)}if(req.method!=='POST')return json(res,405,{error:'method_not_allowed'});let m;try{m=await readJson(req)}catch{return json(res,400,{jsonrpc:'2.0',id:null,error:{code:-32700,message:'Parse error'}})}if(m.method==='notifications/initialized'){res.statusCode=202;return res.end()}const id=m.id??null;try{if(m.method==='initialize')return json(res,200,{jsonrpc:'2.0',id,result:{protocolVersion:m.params?.protocolVersion||'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'discord-reader',version:'0.3.0'}}});if(m.method==='tools/list')return json(res,200,{jsonrpc:'2.0',id,result:{tools}});if(m.method==='tools/call')return json(res,200,{jsonrpc:'2.0',id,result:await callTool(m.params?.name,m.params?.arguments||{})});if(m.method==='ping')return json(res,200,{jsonrpc:'2.0',id,result:{}});json(res,200,{jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found'}});}catch(e){json(res,200,{jsonrpc:'2.0',id,result:{content:[{type:'text',text:String(e?.message||e)}],isError:true}});}}
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.end();const r=route(req);try{if(r==='health')return json(res,200,{ok:true,service:'discord-reader-mcp',version:'0.3.0'});if(r==='resource'){const b=baseUrl(req);return json(res,200,{resource:b,authorization_servers:[b],scopes_supported:[SCOPE],bearer_methods_supported:['header']});}if(r==='authmeta'){const b=baseUrl(req);return json(res,200,{issuer:b,authorization_endpoint:b+'/oauth/authorize',token_endpoint:b+'/oauth/token',registration_endpoint:b+'/oauth/register',response_types_supported:['code'],grant_types_supported:['authorization_code'],code_challenge_methods_supported:['S256'],token_endpoint_auth_methods_supported:['none'],scopes_supported:[SCOPE]});}if(r==='register')return register(req,res);if(r==='authorize')return authorize(req,res);if(r==='token')return token(req,res);if(r==='mcp')return mcp(req,res);return json(res,404,{error:'not_found'});}catch(e){return json(res,500,{error:'server_error',error_description:String(e?.message||e)});}}
